server:
  port: ${PORT:9200}

spring:
  application:
    name: tiers-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  zipkin:
      baseUrl: ${ZIPKIN_URI:http://localhost:9411}
  profiles:
       active: discovery,tracing,standalone,h2
  datasource:
           url: jdbc:h2:mem:tiers-schema;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
           platform: h2
           username: sa
           password:
           driverClassName: org.h2.Driver
  jpa:
           database-platform: org.hibernate.dialect.H2Dialect
           hibernate:
             ddl-auto: update
           properties:
             hibernate:
               show_sql: true
               use_sql_comments: true
               format_sql: true
  h2:
           console:
             enabled: true
             path: /h2console
             settings:
               trace: false
               web-allow-others: false


eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:9000}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true


